spring:
  datasource:
    url: ${datasource_url:jdbc:postgresql://127.0.0.1:5432/hub-job}
    username: ${datasource_username:postgres}
    password: ${datasource_password:postgres}
  liquibase:
    enabled: true
    change-log: sql/changelog.yml
  job:
    server:
      address: localhost:19040
