server:
  port: ${http_port:19030}
  servlet:
    context-path: /meter

spring:
  access:
    filter:
      - /api/v1/*
    auth:
      enable: true
      mode: access-refresh
      ignoreUrls:
        - /favicon.ico
        - /actuator/**
        - /doc/**
        - /api
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/hub-meter
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: sql/changelog.yml

easyopen:
  default-version: 1.0
  ignore-validate: true
  only-json: true
#  interceptors[0]: com.cowave.sys.meter.app.torna.interceptor.DocInterceptor

