spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${datasource_url:jdbc:postgresql://127.0.0.1:5432/hub-admin}
    username: ${datasource_username:postgres}
    password: ${datasource_password:postgres}
  liquibase:
    enabled: true
    change-log: sql/changelog.yml

flowable:
  database-schema-update: true
  admin:
    app:
      security:
        encryption:
          credentialsIVSpec: cowave@123456789
          credentialsSecretSpec: cowave@123456789
  idm:
    app:
      admin:
        first-name: cowave
        last-name: Administrator
        user-id: cowave
        password: cowave@123
        email: shanhuiming@cowave.com
  common:
    app:
      idm-admin:
        user: admin
        password: cowave@123

