spring:
  redis:
    host: ${redis_host:127.0.0.1}
    port: ${redis_port:6379}
  access:
    auth:
      ignore-urls:
        - /admin/api/v1/oauth/client/authorize/token
        - /admin/api/v1/oauth/client/authorize/refresh
        - /admin/api/v1/oauth/client/redirect/**
        - /admin/api/v1/auth/public/**
        - /admin/api/v1/flow/designer/**
        - /admin/designer/**
        - /admin/favicon.ico
        - /admin/actuator/**
        - /admin/doc/**
        - /meter/api
        - /meter/favicon.ico
        - /meter/actuator/**
        - /meter/doc/**
        - /job/favicon.ico
        - /job/actuator/**
        - /job/doc/**
  cloud:
    gateway:
      enabled: true
      routes:
        - id: socket
          uri: lb:ws://hub-admin
          predicates:
            - Path=/socket.io/**
        - id: admin
          uri: lb://hub-admin
          predicates:
            - Path=/admin/**
        - id: job
          uri: lb://hub-job
          predicates:
            - Path=/job/**
        - id: flow
          uri: lb://hub-flow
          predicates:
            - Path=/flow/**
        - id: meter
          uri: lb://hub-meter
          predicates:
            - Path=/meter/**

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  health:
    mail:
      enabled: false
    ping:
      enabled: false
    diskSpace:
      enabled: false
