spring:
  access:
    filter:
      - /api/v1/*
  datasource:
    url: ${datasource_url:jdbc:postgresql://127.0.0.1:5432/hub-meter}
    username: ${datasource_username:postgres}
    password: ${datasource_password:postgres}
  liquibase:
    enabled: true
    change-log: sql/changelog.yml

easyopen:
  default-version: 1.0
  ignore-validate: true
  only-json: true
#  interceptors[0]: com.cowave.sys.meter.app.torna.interceptor.DocInterceptor
