server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: log-hub
  static_configs:
  - targets:
    - localhost
    labels:
      job: log-hub
      host: host-hub
      cluster: hub
      __path__: /home/cowave/hub/hub-*/*.log
  pipeline_stages:
    - match:
        selector: '{job="log-hub"}'
        stages:
        - regex:
           source: filename
           expression: "/home/cowave/hub/(?P<application>\\S+?)/(?P<logger>[^/]+\\.log)$"
        - labels:
            application:
            logger:
